### ISSUE TITLE
doesn't work?

### ISSUE THREAD

**Issue by PengyTheGamer** [Leclowndu93150/Crafting-Station-JEI-Edition#3]
whenever i open the crafting station with jei i get this error and also the button just doesn't appear if i can craft something

[03:52:01] [Render thread/ERROR] [me.je.co.tr.RecipeTransferUtil/]: Transfer request has invalid slots, inventorySlots and craftingSlots should not share any slot, but both have: 1, 2, 3, 4, 5, 6, 7, 8, 9

![image](https://github.com/user-attachments/assets/e1b0830d-3c2f-4326-baef-8a8e97505c3b)

**Comment by Leclowndu93150** [comment]
if you try with an older version of JEI from like 1 month ago is it still broken ?

**Comment by PengyTheGamer** [comment]
using the previous jei version didn't fix it... and the latest jei version is older than the last update for this mod anyway (i think)

but thanks for the quick response

**Comment by Leclowndu93150** [comment]
I'll look into it then

**Comment by PengyTheGamer** [comment]
ty
